# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-01 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='path',
        ),
        migrations.AddField(
            model_name='content',
            name='actualfile',
            field=models.FileField(default=django.utils.timezone.now, upload_to=b'media/'),
            preserve_default=False,
        ),
    ]
