# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-01 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20180401_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='actualfile',
            field=models.FileField(upload_to='files/'),
        ),
    ]
