# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-01 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20180401_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='path',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
