# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-27 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_remove_content_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='ispublic',
            field=models.BooleanField(default=True),
        ),
    ]
