# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-29 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_content_ispublic'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='articleimage',
            field=models.ImageField(blank=True, null=True, upload_to='article-images/'),
        ),
        migrations.AddField(
            model_name='content',
            name='author',
            field=models.CharField(default='auth.User', max_length=25),
        ),
        migrations.AddField(
            model_name='content',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='content',
            name='actualfile',
            field=models.FileField(upload_to='articles/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='ispublic',
            field=models.BooleanField(default=False),
        ),
    ]
