# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-29 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_auto_20180429_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='articleimage',
            field=models.ImageField(default=None, upload_to='article-images/'),
        ),
    ]
